In [1]:
#!pip install easygui

In [1]:
from PIL import Image # Pour la gestion des images

import easygui # Pour ouvrir automatiquement en cliquant  dans une fenêtre de l'explorateur (pas besoin d'indiquer un nom ni un chemin)

#ouvrir l'image avec l'assistant

In [ ]:
myimg = Image.open(easygui.fileopenbox())

#Voir l'image

myimg.show()

In [ ]:
#La voir dans une fenêtre graphique

In [ ]:
import matplotlib.pyplot as plt

plt.imshow(myimg)
plt.show()

In [ ]:
# Convertir l'image au format numpy et la décrire

In [ ]:
import numpy as np

img = np.array(myimg)

plt.imshow(img)
plt.show() # On peut continuer à utiliser la fonction imshow pour visualiser l'image même au format numpy

In [5]:
# Dimensions x, y et nombre de couleurs
print("Dimensions de l'image : ",img.shape) 

Dimensions de l'image :  (1172, 1918, 3)


In [6]:
print("Pixel 500 sur 200 : ",img[200,500])

print("Composante rouge de ce dernier pixel :",img[200,500][0])

Pixel 500 sur 200 :  [106 112 110]
Composante rouge de ce dernier pixel : 106


In [7]:
# Tous le rouge de tous les pixels

print("Rouge : ",img[:,:,0])

Rouge :  [[ 83  83  83 ...  84  80  73]
 [ 86  85  84 ...  84  78  72]
 [ 87  85  83 ...  81  74  71]
 ...
 [ 81  56  42 ...  43  57  61]
 [105  90  77 ...  36  55  55]
 [130 127 124 ...  30  48  39]]


In [ ]:
# Convertir les composantes rouge, vert et bleu en dataframe

In [ ]:
red = np.reshape(img[:,:,0],img.shape[0]*img.shape[1])

green = np.reshape(img[:,:,1],img.shape[0]*img.shape[1])

blue = np.reshape(img[:,:,2],img.shape[0]*img.shape[1])

from pandas import *

couleurs = DataFrame({"r":red,"g":green,"b":blue})

print(couleurs.head(10))

In [ ]:
#Réaliser des transformations sur ces composantes (exemples)

In [ ]:
couleurs = couleurs + 30 # j'éclaircis tout de 30 niveau sur 255

couleurs.r = round(couleurs.r/3,0) # Je divise par 3 les valeurs de rouge

In [ ]:
# Fabriquer une nouvelle image à partir des composantes rouge, vert bleu retravaillée

In [ ]:
img1 = img.copy()

red = np.reshape(np.array(couleurs.r),(img.shape[0],img.shape[1]))

green = np.reshape(np.array(couleurs.g),(img.shape[0],img.shape[1]))

blue = np.reshape(np.array(couleurs.b),(img.shape[0],img.shape[1]))

img1[:,:,0] = red

img1[:,:,1] = green

img1[:,:,2] = blue

In [ ]:
#Afficher comparer l'image avant après

In [ ]:
plt.subplot(121)

plt.imshow(img) 

plt.subplot(122)

plt.imshow(img1) ; plt.show()

In [ ]:
#Une fonction pour faciliter l'affichage en basculant automatiquement en fonction du fait que l'image est en couleur ou en niveau de gris

In [ ]:
def display(img,cmap='gray') :

    if (len(img.shape) == 3) :

       fig, ax = plt.subplots(figsize=(15, 12)) 

       plt.imshow(img) ; plt.show()

    else :

       fig, ax = plt.subplots(figsize=(15, 12)) 

       plt.imshow(img,cmap=cmap, vmin=0, vmax=255) ; plt.show()

In [ ]:
#Une fonction pour convertir une image en niveau de gris

###############################

#   NiVEAU DE GRIS

###############################

In [ ]:
def gray_scale_img(img) :

    temp_img = img[:,:,1]

    temp_img = temp_img.reshape(temp_img.shape[0],temp_img.shape[1])

    temp_img[:,:] <- img[:,:,0]*0.2126+img[:,:,1]*0.7152+img[:,:,2]*0.0722

    return(temp_img)

img_grey = gray_scale_img(img)
display(img_grey)